on: push
name: golang-ci
jobs:
  checks:
    name: run-test2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEW_DOG }}
        run: |
          reviewdog -reporter=github-pr-check -runners=golint,govet


